# Copyright 2020 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Sex stratified pipeline configuration

schema:
  date: str
  key: str
  new_confirmed_male: int
  new_confirmed_female: int
  total_confirmed_male: int
  total_confirmed_female: int
  new_deceased_male: int
  new_deceased_female: int
  total_deceased_male: int
  total_deceased_female: int
  new_recovered_male: int
  new_recovered_female: int
  total_recovered_male: int
  total_recovered_female: int
  new_tested_male: int
  new_tested_female: int
  total_tested_male: int
  total_tested_female: int
  new_hospitalized_male: int
  new_hospitalized_female: int
  total_hospitalized_male: int
  total_hospitalized_female: int
  new_intensive_care_male: int
  new_intensive_care_female: int
  total_intensive_care_male: int
  total_intensive_care_female: int
  new_ventilator_male: int
  new_ventilator_female: int
  total_ventilator_male: int
  total_ventilator_female: int

auxiliary:
  metadata: ./data/metadata.csv
  localities: ./data/localities.csv
  country_codes: ./data/country_codes.csv
  knowledge_graph: ./data/knowledge_graph.csv

sources:

  # Data sources for AR levels 2 + 3
  - class: pipelines.epidemiology.ar_authority.ArgentinaDataSource
    label: Datos Argentina
    fetch:
      - url: "https://sisa.msal.gov.ar/datos/descargas/covid-19/files/Covid19Casos.csv"
    test:
      # Skip because it's too slow
      skip: true
      location_key_match: 'AR_.*'

  # Data sources for BR levels 1 + 2 + 3
  - class: pipelines.epidemiology.br_authority.BrazilOpenDataPortalDataSource
    label: Ministry of Health of Brazil (openDataSUS)
    fetch:
      - url: "https://s3-sa-east-1.amazonaws.com/ckan.saude.gov.br/dados-{0}.csv"
    parse:
      sep: ";"
      encoding: "ISO-8859-1"
      # This data source does not report zero values, so we fill them in
      fill_with_zeroes: ['new_[^_]+_male', 'new_[^_]+_female']
    test:
      location_key_match:
        - '^BR$'
        - '^BR_[^_]+$'
        - '^BR_[^_]+_[^_]+$'
      # Skip because it's too slow
      skip: true

  - class: pipelines.epidemiology.br_authority.BrazilSRAGDataSource
    label: Ministry of Health of Brazil (SRAG)
    fetch:
      - url: "https://s3-sa-east-1.amazonaws.com/ckan.saude.gov.br/SRAG/2020/INFLUD-{date}.csv"
        opts:
          date_format: '%d-%m-%Y'
    parse:
      sep: ";"
      encoding: "ISO-8859-1"
      # This data source does not report zero values, so we fill them in
      fill_with_zeroes: ['new_[^_]+_male', 'new_[^_]+_female']
    test:
      location_key_match:
        - '^BR$'
        - '^BR_[^_]+$'
        - '^BR_[^_]+_[^_]+$'
      # Skip because it's too slow
      skip: true

  - class: pipelines.epidemiology.br_authority.BrazilSRAGDataSource
    label: Ministry of Health of Brazil (SRAG)
    fetch:
      - url: "https://s3-sa-east-1.amazonaws.com/ckan.saude.gov.br/SRAG/2021/INFLUD21-{date}.csv"
        opts:
          date_format: '%d-%m-%Y'
    parse:
      sep: ";"
      encoding: "ISO-8859-1"
      # This data source does not report zero values, so we fill them in
      fill_with_zeroes: ['new_[^_]+_male', 'new_[^_]+_female']
    test:
      location_key_match:
        - '^BR$'
        - '^BR_[^_]+$'
        - '^BR_[^_]+_[^_]+$'
      # Skip because it's too slow
      skip: true

  # Data sources for BR_RJ level 3
  - class: pipelines.epidemiology.br_rj_authority.RioStratifiedDataSource
    label: Ministry of Health of Rio de Janeiro
    fetch:
      - url: "https://pcrj.maps.arcgis.com/sharing/rest/content/items/754cc0698129404ba8bfb053cbdbd158/data"
        opts:
          ext: csv
    parse:
      sep: ";"
      encoding: "ISO-8859-1"
    test:
      location_key_match: '^BR_RJ_GIG$'
      # Skip because it's very flakey
      skip: true

  # Data sources for CO levels 1 + 2 + 3
  - class: pipelines.epidemiology.co_authority.ColombiaDataSource
    label: Ministry of Health of Colombia
    fetch:
      - url: "https://www.datos.gov.co/api/views/gt2j-8ykr/rows.csv"
    test:
      location_key_match: 'CO.*'

  # Data sources for CZ levels 1 + 2 + 3
  - class: pipelines.epidemiology.cz_authority.CzechRepublicAgeSexDataSource
    label: Ministry of Health of the Czech Republic
    fetch:
      - url: "https://onemocneni-aktualne.mzcr.cz/api/v2/covid-19/osoby.csv"
    parse:
      column_name: 'new_confirmed'
      # This data source contains case line data, so any missing information means zero
      fill_with_zeroes: ['new_[^_]+_male', 'new_[^_]+_female']
    test:
      location_key_match: 'CZ.*'

  - class: pipelines.epidemiology.cz_authority.CzechRepublicAgeSexDataSource
    label: Ministry of Health of the Czech Republic
    fetch:
      - url: "https://onemocneni-aktualne.mzcr.cz/api/v2/covid-19/umrti.csv"
    parse:
      column_name: 'new_deceased'
      # This data source contains case line data, so any missing information means zero
      fill_with_zeroes: ['new_[^_]+_male', 'new_[^_]+_female']
    test:
      location_key_match: 'CZ.*'

  - class: pipelines.epidemiology.cz_authority.CzechRepublicAgeSexDataSource
    label: Ministry of Health of the Czech Republic
    fetch:
      - url: "https://onemocneni-aktualne.mzcr.cz/api/v2/covid-19/vyleceni.csv"
    parse:
      column_name: 'new_recovered'
      # This data source contains case line data, so any missing information means zero
      fill_with_zeroes: ['new_[^_]+_male', 'new_[^_]+_female']
    test:
      location_key_match: 'CZ.*'

  # Data sources for DE levels 0 + 1 + 2
  - class: pipelines.epidemiology.de_authority.GermanyDataSource
    label: Robert Koch Institute
    fetch:
      - url: "https://opendata.arcgis.com/datasets/dd4580c810204019a7b8eb3e0b329dd6_0.csv"
    parse:
      # This data source contains case line data, so any missing information means zero
      fill_with_zeroes: ['new_[^_]+_male', 'new_[^_]+_female']
    test:
      location_key_match:
        - '^DE$'
        - '^DE_[^_]+$'
        - '^DE_[^_]+_[^_]+$'

  # Data sources for EE levels 0 + 1
  - class: pipelines.epidemiology.ee_authority.EstoniaDataSource
    label: Health Board of Estonia
    fetch:
      - url: "https://opendata.digilugu.ee/opendata_covid19_test_results.csv"
    parse:
      dtype: str
      # This data source does not report zero values, so we fill them in
      fill_with_zeroes: ['new_[^_]+_male', 'new_[^_]+_female']
    test:
      location_key_match:
        - '^EE+$'
        - '^EE_[^_]+$'

  # Data sources for ES levels 0 + 1
  - class: pipelines.epidemiology.es_authority.ISCIIIStratifiedDataSource
    label: Ministry of Health of Spain
    fetch:
      - url: "https://cnecovid.isciii.es/covid19/resources/casos_hosp_uci_def_sexo_edad_provres.csv"
    test:
      location_key_match:
        - '^ES$'
        - '^ES_[^_]+$'

  # Data sources for ES_CT levels 2 + 3
  - class: pipelines.epidemiology.es_ct_authority.CataloniaMunicipalitiesDataSource
    label: Department of Health of Catalonia
    fetch:
      - url: "https://analisi.transparenciacatalunya.cat/api/views/jj6z-iyrp/rows.csv"
    parse:
      dtype: str
    test:
      location_key_match: 'ES_CT.*'

  # Data sources for FI level 1
  - class: pipelines.epidemiology.fi_authority.FinlandArcGisDataSource
    label: Finnish Institute for Health and Welfare
    fetch:
      - url: https://services7.arcgis.com/nuPvVz1HGGfa0Eh7/arcgis/rest/services/korona_tapauksia_jakauma/FeatureServer/0/query?f=json&where=1%3D1&outFields=OBJECTID,alue,date,tapauksia,miehia,naisia,Ika_0_9,ika_10_19,ika_20_29,ika_30_39,ika_40_49,ika_50_59,ika_60_69,ika_70_79,ika_80_,koodi&returnGeometry=false
        opts:
          ext: json
    query: "date > '2020-02-01'"
    test:
      location_key_match: '^FI$'

  # Data sources for FR levels 1 + 2 + 3
  - class: pipelines.epidemiology.fr_authority.FranceStratifiedDataSource
    label: Etalab
    fetch:
      - url: https://dashboard.covid19.data.gouv.fr/data/code-{}.json
    test:
      location_key_match:
        - '^FR$'
        - '^FR_[^_]+$'
        - '^FR_[^_]+_[^_]+$'

  # Data sources for HK level 0
  - class: pipelines.epidemiology.hk_authority.HongKongDataSource
    label: Hong Kong Department of Health
    fetch:
      - url: "https://www.chp.gov.hk/files/misc/enhanced_sur_covid_19_eng.csv"
    parse:
      # This data source does not report zero values, so we fill them in
      fill_with_zeroes: ['new_[^_]+_male', 'new_[^_]+_female']
    test:
      location_key_match: '^HK$'

  # Data source for IN levels 0 + 1
  - class: pipelines.epidemiology.in_covid19india_org.Covid19IndiaOrgCasesDataSource
    label: covid19india.org
    fetch:
      - url: "https://api.covid19india.org/csv/latest/raw_data{idx}.csv"
        opts:
          ext: csv
    test:
      location_key_match:
        - '^IN$'
        - '^IN_[^_]+$'

  # Data sources for MX levels 1, 2 and 3
  - class: pipelines.epidemiology.mx_authority.MexicoDataSource
    label: Ministry of Health of Mexico
    website: https://coronavirus.gob.mx/
    fetch:
      - url: "http://datosabiertos.salud.gob.mx/gobmx/salud/datos_abiertos/datos_abiertos_covid19.zip"
    parse:
      encoding: "ISO-8859-1"
      # This data source does not report zero values, so we fill them in
      fill_with_zeroes: ['new_[^_]+_male', 'new_[^_]+_female']
    test:
      # Skip this data source because it's too slow
      skip: true
      location_key_match:
        - '^MX$'
        - '^MX_[^_]+$'
        - '^MX_[^_]+_[^_]+$'

  # Data sources for NZ level 0
  - class: pipelines.epidemiology.nz_authority.NewZealandDataSource
    label: Ministry of Health of New Zealand
    fetch:
      - url: "https://www.health.govt.nz/system/files/documents/pages/covid_cases_{date}.csv"
        opts:
          date_format: '%Y-%m-%d'
    parse:
      # This data source does not report zero values, so we fill them in
      fill_with_zeroes: ['new_[^_]+_male', 'new_[^_]+_female']
    test:
      location_key_match: '^NZ$'
      # Skip because it's flakey
      skip: true

  # Data sources for PE levels 1 + 2 + 3
  - class: pipelines.epidemiology.pe_authority.PeruDataSource
    label: Ministry of Health of Peru
    fetch:
      - name: confirmed
        url: "https://cloud.minsa.gob.pe/s/Y8w3wHsEdYQSZRp/download"
        opts:
          ext: csv
      - name: deceased
        url: "https://cloud.minsa.gob.pe/s/Md37cjXmjT9qYSa/download"
        opts:
          ext: csv
    parse:
      encoding: "ISO-8859-1"
      sep: ";"
    test:
      location_key_match: 'PE.*'
      # Skip because this is a flakey data source
      skip: true

  # Data sources for PH levels 2 + 3
  - class: pipelines.epidemiology.ph_authority.PhilippinesDataSource
    label: Open Data Philippines (ODPH)
    website: https://data.gov.ph/?q=search&query=covid
    fetch:
      - url: "https://data.gov.ph/sites/default/files/DOH%20COVID%20Data%20Drop_%20{date}%20-%2004%20Case%20Information.csv"
    test:
      location_key_match:
        - '^PH$'
        - '^PH_[^_]+$'
        - '^PH_[^_]+_[^_]+$'

  # Data sources for TH levels 0 + 1
  - class: pipelines.epidemiology.th_authority.ThailandCasesDataSource
    label: Thailand Department of Desease Control
    website: https://ddc.moph.go.th/viralpneumonia/
    fetch:
      - url: "https://data.go.th/dataset/8a956917-436d-4afd-a2d4-59e4dd8e906e/resource/67d43695-8626-45ad-9094-dabc374925ab/download/confirmed-cases.xlsx"
    test:
      location_key_match:
        - '^TH$'
        - '^TH_[^_]+$'

  # Data sources for TW levels 0 + 1
  - class: pipelines.epidemiology.tw_authority.TaiwanDataSource
    label: Ministry of Health and Welfare of Taiwan
    fetch:
      - url: "https://od.cdc.gov.tw/eic/Day_Confirmation_Age_County_Gender_19CoV.csv"
    parse:
      # This data source does not report zero values, so we fill them in
      fill_with_zeroes: ['new_[^_]+_male', 'new_[^_]+_female']
    test:
      location_key_match:
        - '^TW$'
        - '^TW_[^_]+$'
      # Skip because it's too flakey
      skip: true

  # Data sources for US_DC level 2
  - class: pipelines.epidemiology.us_dc_authority.DistrictColumbiaDataSource
    label: Government of the District of Columbia
    fetch:
      - url: "https://coronavirus.dc.gov/page/coronavirus-data"
        opts:
          ext: xlsx
    parse:
      sheet_name: "Lives Lost by Sex"
    test:
      # Skip because it's too flakey
      skip: true
      location_key_match: '^US_DC$'

  # Data sources for US_DE level 2
  - class: pipelines.epidemiology.us_de_authority.DelawareDataSource
    label: Delaware Health and Social Services
    fetch:
      - url: "https://myhealthycommunity.dhss.delaware.gov/locations/state/download_covid_19_data"
        opts:
          ext: csv
          spoof_browser: false
    test:
      location_key_match: '^US_DE$'
      # Skip because endpoint fails frequently
      skip: true

  # Data sources US_FL levels 1 + 2
  - class: pipelines.epidemiology.us_fl_authority.FloridaDataSource
    label: Florida Health
    fetch:
      - url: "https://services1.arcgis.com/CY1LXxl9zlJeBuRZ/ArcGIS/rest/services/Florida_COVID19_Case_Line_Data_NEW/FeatureServer/0/query?where=1%3D1&outFields=*&f=json"
    parse:
      # This data source does not report zero values, so we fill them in
      fill_with_zeroes: ['new_[^_]+_male', 'new_[^_]+_female']
    test:
      location_key_match:
        - '^US_FL$'
        - '^US_FL_[^_]+$'
      # Skip Florida because download takes a long time
      skip: true

  # Data sources for US_IN level 3
  - class: pipelines.epidemiology.us_in_authority.IndianaDataSource
    label: Indiana Department of Health
    fetch:
      - url: "https://hub.mph.in.gov/dataset/6b57a4f2-b754-4f79-a46b-cff93e37d851/resource/46b310b9-2f29-4a51-90dc-3886d9cf4ac1/download/covid_report.xlsx"
        opts:
          ext: xlsx
    # Only aggregate age/sex pipelines to state level because the data does not add up to the total
    # number of cases. This is because small case counts are excluded for privacy reasons.
    aggregate:
      subregion2: ['new_confirmed_age_*']
    parse:
      # This data source does not report zero values, so we fill them in
      fill_with_zeroes: ['new_confirmed_age_*']
    test:
      location_key_match: 'US_IN.*'

  # Data sources for US_MA level 3
  - class: pipelines.epidemiology.us_ma_authority.MassachusettsBySexDataSource
    label: MCAD COVID-19 Information & Resource Center
    fetch:
      - name: by-sex
        # August 11th was the last day US_MA reported cases broken down by age/sex
        url: "https://www.mass.gov/doc/covid-19-raw-data-august-11-2020/download"
        opts:
          ext: zip
    parse:
      file_name: Sex.csv
    test:
      location_key_match: '^US_MA$'
